# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyengo', '0003_auto_20160519_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpaymentresult',
            name='result_code',
            field=models.CharField(choices=[('Authorised', 'Authorised'), ('Error', 'Error'), ('Refused', 'Refused')], max_length=30),
        ),
        migrations.AlterField(
            model_name='session',
            name='country_code',
            field=models.CharField(blank=True, choices=[('NL', 'Netherlands'), ('BE', 'Belgium'), ('GB', 'United Kingdom'), ('DE', 'Germany')], max_length=2),
        ),
        migrations.AlterField(
            model_name='session',
            name='recurring_contract',
            field=models.CharField(blank=True, choices=[('ONECLICK', 'One click'), ('RECURRING', 'Recurring'), ('RECURRING,ONECLICK', 'Recurring and One click (user chooses)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('api_recurring', 'API Recurring'), ('hpp_regular', 'HPP Regular'), ('hpp_recurring', 'HPP Recurring')], max_length=25),
        ),
        migrations.AlterField(
            model_name='session',
            name='shopper_locale',
            field=models.CharField(blank=True, choices=[('fr_BE', 'French (Belgium)'), ('en_GB', 'English (United Kingdom)'), ('nl_NL', 'Dutch (Holland)'), ('nl_BE', 'Dutch (Belgium)'), ('de_DE', 'German (Germany)')], default='nl_NL', max_length=5),
        ),
        migrations.AlterField(
            model_name='sessionallowedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('bankTransfer', 'All banktransfers'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('elv', 'ELV'), ('visa', 'Visa'), ('mc', 'Master Card'), ('card', 'All debit and credit cards'), ('directEbanking', 'SofortUberweisung'), ('amex', 'Amex'), ('bankTransfer_DE', 'German Banktransfer'), ('ideal', 'iDEAL'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('paypal', 'PayPal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionblockedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('bankTransfer', 'All banktransfers'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('elv', 'ELV'), ('visa', 'Visa'), ('mc', 'Master Card'), ('card', 'All debit and credit cards'), ('directEbanking', 'SofortUberweisung'), ('amex', 'Amex'), ('bankTransfer_DE', 'German Banktransfer'), ('ideal', 'iDEAL'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('paypal', 'PayPal')], max_length=50),
        ),
    ]
