# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyengo', '0004_auto_20160526_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='valid',
        ),
        migrations.AddField(
            model_name='notification',
            name='currency_code',
            field=models.CharField(choices=[('EUR', 'Euro')], default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='notification',
            name='payment_amount',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bankTransfer_NL', 'Dutch Banktransfer'), ('bankTransfer', 'All banktransfers'), ('bankTransfer_DE', 'German Banktransfer'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('directEbanking', 'SofortUberweisung'), ('visa', 'Visa'), ('ideal', 'iDEAL'), ('mc', 'Master Card'), ('elv', 'ELV'), ('paypal', 'PayPal'), ('amex', 'Amex'), ('card', 'All debit and credit cards')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringpaymentresult',
            name='result_code',
            field=models.CharField(choices=[('Error', 'Error'), ('Authorised', 'Authorised'), ('Refused', 'Refused')], max_length=30),
        ),
        migrations.AlterField(
            model_name='session',
            name='country_code',
            field=models.CharField(blank=True, choices=[('NL', 'Netherlands'), ('BE', 'Belgium'), ('DE', 'Germany'), ('GB', 'United Kingdom')], max_length=2),
        ),
        migrations.AlterField(
            model_name='session',
            name='currency_code',
            field=models.CharField(choices=[('EUR', 'Euro')], default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='session',
            name='page_type',
            field=models.CharField(choices=[('multiple', 'Multiple'), ('single', 'Single'), ('skip', 'Skip')], default='multiple', max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='recurring_contract',
            field=models.CharField(blank=True, choices=[('ONECLICK', 'One click'), ('RECURRING,ONECLICK', 'Recurring and One click (user chooses)'), ('RECURRING', 'Recurring')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='res_url',
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='session',
            name='shopper_locale',
            field=models.CharField(blank=True, choices=[('de_DE', 'German (Germany)'), ('nl_BE', 'Dutch (Belgium)'), ('fr_BE', 'French (Belgium)'), ('nl_NL', 'Dutch (Holland)'), ('en_GB', 'English (United Kingdom)')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='session',
            name='skin_code',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='sessionallowedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('bankTransfer_NL', 'Dutch Banktransfer'), ('bankTransfer', 'All banktransfers'), ('bankTransfer_DE', 'German Banktransfer'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('directEbanking', 'SofortUberweisung'), ('visa', 'Visa'), ('ideal', 'iDEAL'), ('mc', 'Master Card'), ('elv', 'ELV'), ('paypal', 'PayPal'), ('amex', 'Amex'), ('card', 'All debit and credit cards')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionblockedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('bankTransfer_NL', 'Dutch Banktransfer'), ('bankTransfer', 'All banktransfers'), ('bankTransfer_DE', 'German Banktransfer'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('directEbanking', 'SofortUberweisung'), ('visa', 'Visa'), ('ideal', 'iDEAL'), ('mc', 'Master Card'), ('elv', 'ELV'), ('paypal', 'PayPal'), ('amex', 'Amex'), ('card', 'All debit and credit cards')], max_length=50),
        ),
    ]
