# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyengo', '0005_auto_20160527_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('card', 'All debit and credit cards'), ('bankTransfer_DE', 'German Banktransfer'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('visa', 'Visa'), ('ideal', 'iDEAL'), ('bankTransfer', 'All banktransfers'), ('directEbanking', 'SofortUberweisung'), ('elv', 'ELV'), ('mc', 'Master Card'), ('amex', 'Amex')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringpaymentresult',
            name='result_code',
            field=models.CharField(choices=[('Authorised', 'Authorised'), ('Refused', 'Refused'), ('Error', 'Error')], max_length=30),
        ),
        migrations.AlterField(
            model_name='session',
            name='country_code',
            field=models.CharField(blank=True, choices=[('GB', 'United Kingdom'), ('NL', 'Netherlands'), ('DE', 'Germany'), ('BE', 'Belgium')], max_length=2),
        ),
        migrations.AlterField(
            model_name='session',
            name='page_type',
            field=models.CharField(choices=[('single', 'Single'), ('skip', 'Skip'), ('multiple', 'Multiple')], default='multiple', max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='recurring_contract',
            field=models.CharField(blank=True, choices=[('RECURRING,ONECLICK', 'Recurring and One click (user chooses)'), ('RECURRING', 'Recurring'), ('ONECLICK', 'One click')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('hpp_recurring', 'HPP Recurring'), ('api_recurring', 'API Recurring'), ('hpp_regular', 'HPP Regular')], max_length=25),
        ),
        migrations.AlterField(
            model_name='session',
            name='shopper_locale',
            field=models.CharField(blank=True, choices=[('en_GB', 'English (United Kingdom)'), ('nl_NL', 'Dutch (Holland)'), ('de_DE', 'German (Germany)'), ('fr_BE', 'French (Belgium)'), ('nl_BE', 'Dutch (Belgium)')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='sessionallowedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('card', 'All debit and credit cards'), ('bankTransfer_DE', 'German Banktransfer'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('visa', 'Visa'), ('ideal', 'iDEAL'), ('bankTransfer', 'All banktransfers'), ('directEbanking', 'SofortUberweisung'), ('elv', 'ELV'), ('mc', 'Master Card'), ('amex', 'Amex')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionblockedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('card', 'All debit and credit cards'), ('bankTransfer_DE', 'German Banktransfer'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('visa', 'Visa'), ('ideal', 'iDEAL'), ('bankTransfer', 'All banktransfers'), ('directEbanking', 'SofortUberweisung'), ('elv', 'ELV'), ('mc', 'Master Card'), ('amex', 'Amex')], max_length=50),
        ),
    ]
