# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyengo', '0007_auto_20160527_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('directdebit_NL', 'Direct Debit (Netherlands)'), ('ideal', 'iDEAL'), ('paypal', 'PayPal'), ('mc', 'Master Card'), ('elv', 'ELV'), ('amex', 'Amex'), ('bankTransfer_DE', 'German Banktransfer'), ('bankTransfer', 'All banktransfers'), ('card', 'All debit and credit cards'), ('visa', 'Visa'), ('directEbanking', 'SofortUberweisung'), ('bankTransfer_NL', 'Dutch Banktransfer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recurringpaymentresult',
            name='result_code',
            field=models.CharField(choices=[('Refused', 'Refused'), ('Error', 'Error'), ('Authorised', 'Authorised')], max_length=30),
        ),
        migrations.AlterField(
            model_name='session',
            name='country_code',
            field=models.CharField(blank=True, choices=[('GB', 'United Kingdom'), ('NL', 'Netherlands'), ('DE', 'Germany'), ('BE', 'Belgium')], max_length=2),
        ),
        migrations.AlterField(
            model_name='session',
            name='page_type',
            field=models.CharField(choices=[('skip', 'Skip'), ('multiple', 'Multiple'), ('single', 'Single')], default='multiple', max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='recurring_contract',
            field=models.CharField(blank=True, choices=[('ONECLICK', 'One click'), ('RECURRING', 'Recurring'), ('RECURRING,ONECLICK', 'Recurring and One click (user chooses)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='shopper_locale',
            field=models.CharField(blank=True, choices=[('nl_NL', 'Dutch (Holland)'), ('nl_BE', 'Dutch (Belgium)'), ('fr_BE', 'French (Belgium)'), ('de_DE', 'German (Germany)'), ('en_GB', 'English (United Kingdom)')], default='nl_NL', max_length=5),
        ),
        migrations.AlterField(
            model_name='sessionallowedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('directdebit_NL', 'Direct Debit (Netherlands)'), ('ideal', 'iDEAL'), ('paypal', 'PayPal'), ('mc', 'Master Card'), ('elv', 'ELV'), ('amex', 'Amex'), ('bankTransfer_DE', 'German Banktransfer'), ('bankTransfer', 'All banktransfers'), ('card', 'All debit and credit cards'), ('visa', 'Visa'), ('directEbanking', 'SofortUberweisung'), ('bankTransfer_NL', 'Dutch Banktransfer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionblockedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('directdebit_NL', 'Direct Debit (Netherlands)'), ('ideal', 'iDEAL'), ('paypal', 'PayPal'), ('mc', 'Master Card'), ('elv', 'ELV'), ('amex', 'Amex'), ('bankTransfer_DE', 'German Banktransfer'), ('bankTransfer', 'All banktransfers'), ('card', 'All debit and credit cards'), ('visa', 'Visa'), ('directEbanking', 'SofortUberweisung'), ('bankTransfer_NL', 'Dutch Banktransfer')], max_length=50),
        ),
    ]
