# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyengo', '0008_auto_20160527_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('amex', 'Amex'), ('elv', 'ELV'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('paypal', 'PayPal'), ('directEbanking', 'SofortUberweisung'), ('card', 'All debit and credit cards'), ('visa', 'Visa'), ('bankTransfer_DE', 'German Banktransfer'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('bankTransfer', 'All banktransfers'), ('ideal', 'iDEAL'), ('mc', 'Master Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recurringpaymentresult',
            name='result_code',
            field=models.CharField(choices=[('Authorised', 'Authorised'), ('Error', 'Error'), ('Refused', 'Refused')], max_length=30),
        ),
        migrations.AlterField(
            model_name='session',
            name='country_code',
            field=models.CharField(blank=True, choices=[('DE', 'Germany'), ('GB', 'United Kingdom'), ('NL', 'Netherlands'), ('BE', 'Belgium')], max_length=2),
        ),
        migrations.AlterField(
            model_name='session',
            name='page_type',
            field=models.CharField(choices=[('single', 'Single'), ('skip', 'Skip'), ('multiple', 'Multiple')], default='multiple', max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='recurring_contract',
            field=models.CharField(blank=True, choices=[('RECURRING,ONECLICK', 'Recurring and One click (user chooses)'), ('RECURRING', 'Recurring'), ('ONECLICK', 'One click')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('hpp_regular', 'HPP Regular'), ('api_recurring', 'API Recurring'), ('hpp_recurring', 'HPP Recurring')], max_length=25),
        ),
        migrations.AlterField(
            model_name='session',
            name='shopper_locale',
            field=models.CharField(blank=True, choices=[('de_DE', 'German (Germany)'), ('en_GB', 'English (United Kingdom)'), ('nl_NL', 'Dutch (Holland)'), ('nl_BE', 'Dutch (Belgium)'), ('fr_BE', 'French (Belgium)')], default='nl_NL', max_length=5),
        ),
        migrations.AlterField(
            model_name='sessionallowedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('amex', 'Amex'), ('elv', 'ELV'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('paypal', 'PayPal'), ('directEbanking', 'SofortUberweisung'), ('card', 'All debit and credit cards'), ('visa', 'Visa'), ('bankTransfer_DE', 'German Banktransfer'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('bankTransfer', 'All banktransfers'), ('ideal', 'iDEAL'), ('mc', 'Master Card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionblockedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('amex', 'Amex'), ('elv', 'ELV'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('paypal', 'PayPal'), ('directEbanking', 'SofortUberweisung'), ('card', 'All debit and credit cards'), ('visa', 'Visa'), ('bankTransfer_DE', 'German Banktransfer'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('bankTransfer', 'All banktransfers'), ('ideal', 'iDEAL'), ('mc', 'Master Card')], max_length=50),
        ),
    ]
