# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyengo', '0010_auto_20160528_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bankTransfer_NL', 'Dutch Banktransfer'), ('paypal', 'PayPal'), ('visa', 'Visa'), ('elv', 'ELV'), ('amex', 'Amex'), ('ideal', 'iDEAL'), ('bankTransfer', 'All banktransfers'), ('card', 'All debit and credit cards'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('mc', 'Master Card'), ('bankTransfer_DE', 'German Banktransfer'), ('directEbanking', 'SofortUberweisung')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recurringpaymentresult',
            name='result_code',
            field=models.CharField(choices=[('Refused', 'Refused'), ('Error', 'Error'), ('Authorised', 'Authorised')], max_length=30),
        ),
        migrations.AlterField(
            model_name='session',
            name='country_code',
            field=models.CharField(choices=[('NL', 'Netherlands'), ('GB', 'United Kingdom'), ('BE', 'Belgium'), ('DE', 'Germany')], max_length=2),
        ),
        migrations.AlterField(
            model_name='session',
            name='page_type',
            field=models.CharField(choices=[('multiple', 'Multiple'), ('single', 'Single'), ('skip', 'Skip')], default='multiple', max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='res_url',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='shopper_locale',
            field=models.CharField(blank=True, choices=[('nl_NL', 'Dutch (Holland)'), ('fr_BE', 'French (Belgium)'), ('nl_BE', 'Dutch (Belgium)'), ('de_DE', 'German (Germany)'), ('en_GB', 'English (United Kingdom)')], default='nl_NL', max_length=5),
        ),
        migrations.AlterField(
            model_name='sessionallowedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('bankTransfer_NL', 'Dutch Banktransfer'), ('paypal', 'PayPal'), ('visa', 'Visa'), ('elv', 'ELV'), ('amex', 'Amex'), ('ideal', 'iDEAL'), ('bankTransfer', 'All banktransfers'), ('card', 'All debit and credit cards'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('mc', 'Master Card'), ('bankTransfer_DE', 'German Banktransfer'), ('directEbanking', 'SofortUberweisung')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionblockedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('bankTransfer_NL', 'Dutch Banktransfer'), ('paypal', 'PayPal'), ('visa', 'Visa'), ('elv', 'ELV'), ('amex', 'Amex'), ('ideal', 'iDEAL'), ('bankTransfer', 'All banktransfers'), ('card', 'All debit and credit cards'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('mc', 'Master Card'), ('bankTransfer_DE', 'German Banktransfer'), ('directEbanking', 'SofortUberweisung')], max_length=50),
        ),
    ]
