# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyengo', '0013_auto_20160707_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bankTransfer_NL', 'Dutch Banktransfer'), ('directEbanking', 'SofortUberweisung'), ('visa', 'Visa'), ('bankTransfer', 'All banktransfers'), ('amex', 'Amex'), ('paypal', 'PayPal'), ('mc', 'Master Card'), ('bankTransfer_DE', 'German Banktransfer'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('ideal', 'iDEAL'), ('card', 'All debit and credit cards'), ('elv', 'ELV')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recurringpaymentresult',
            name='result_code',
            field=models.CharField(choices=[('Received', 'Received'), ('Error', 'Error'), ('Refused', 'Refused'), ('Authorised', 'Authorised')], max_length=30),
        ),
        migrations.AlterField(
            model_name='session',
            name='country_code',
            field=models.CharField(choices=[('BE', 'Belgium'), ('NL', 'Netherlands'), ('DE', 'Germany'), ('GB', 'United Kingdom')], max_length=2),
        ),
        migrations.AlterField(
            model_name='session',
            name='page_type',
            field=models.CharField(choices=[('skip', 'Skip'), ('multiple', 'Multiple'), ('single', 'Single')], default='multiple', max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='recurring_contract',
            field=models.CharField(blank=True, choices=[('ONECLICK', 'One click'), ('RECURRING,ONECLICK', 'Recurring and One click (user chooses)'), ('RECURRING', 'Recurring')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='shopper_locale',
            field=models.CharField(blank=True, choices=[('de_DE', 'German (Germany)'), ('en_GB', 'English (United Kingdom)'), ('fr_BE', 'French (Belgium)'), ('nl_BE', 'Dutch (Belgium)'), ('nl_NL', 'Dutch (Holland)')], default='nl_NL', max_length=5),
        ),
        migrations.AlterField(
            model_name='sessionallowedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('bankTransfer_NL', 'Dutch Banktransfer'), ('directEbanking', 'SofortUberweisung'), ('visa', 'Visa'), ('bankTransfer', 'All banktransfers'), ('amex', 'Amex'), ('paypal', 'PayPal'), ('mc', 'Master Card'), ('bankTransfer_DE', 'German Banktransfer'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('ideal', 'iDEAL'), ('card', 'All debit and credit cards'), ('elv', 'ELV')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionblockedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('bankTransfer_NL', 'Dutch Banktransfer'), ('directEbanking', 'SofortUberweisung'), ('visa', 'Visa'), ('bankTransfer', 'All banktransfers'), ('amex', 'Amex'), ('paypal', 'PayPal'), ('mc', 'Master Card'), ('bankTransfer_DE', 'German Banktransfer'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('ideal', 'iDEAL'), ('card', 'All debit and credit cards'), ('elv', 'ELV')], max_length=50),
        ),
    ]
