# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyengo', '0014_auto_20160707_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ideal', 'iDEAL'), ('visa', 'Visa'), ('elv', 'ELV'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('card', 'All debit and credit cards'), ('bankTransfer', 'All banktransfers'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('directEbanking', 'SofortUberweisung'), ('amex', 'Amex'), ('mc', 'Master Card'), ('paypal', 'PayPal'), ('bankTransfer_DE', 'German Banktransfer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='country_code',
            field=models.CharField(choices=[('GB', 'United Kingdom'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('DE', 'Germany')], max_length=2),
        ),
        migrations.AlterField(
            model_name='session',
            name='page_type',
            field=models.CharField(choices=[('single', 'Single'), ('skip', 'Skip'), ('multiple', 'Multiple')], default='multiple', max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='recurring_contract',
            field=models.CharField(blank=True, choices=[('RECURRING', 'Recurring'), ('ONECLICK', 'One click'), ('RECURRING,ONECLICK', 'Recurring and One click (user chooses)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('api_recurring', 'API Recurring'), ('hpp_regular', 'HPP Regular'), ('hpp_recurring', 'HPP Recurring')], max_length=25),
        ),
        migrations.AlterField(
            model_name='session',
            name='shopper_locale',
            field=models.CharField(blank=True, choices=[('de_DE', 'German (Germany)'), ('nl_BE', 'Dutch (Belgium)'), ('nl_NL', 'Dutch (Holland)'), ('en_GB', 'English (United Kingdom)'), ('fr_BE', 'French (Belgium)')], default='nl_NL', max_length=5),
        ),
        migrations.AlterField(
            model_name='sessionallowedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('ideal', 'iDEAL'), ('visa', 'Visa'), ('elv', 'ELV'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('card', 'All debit and credit cards'), ('bankTransfer', 'All banktransfers'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('directEbanking', 'SofortUberweisung'), ('amex', 'Amex'), ('mc', 'Master Card'), ('paypal', 'PayPal'), ('bankTransfer_DE', 'German Banktransfer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionblockedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('ideal', 'iDEAL'), ('visa', 'Visa'), ('elv', 'ELV'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('card', 'All debit and credit cards'), ('bankTransfer', 'All banktransfers'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('directEbanking', 'SofortUberweisung'), ('amex', 'Amex'), ('mc', 'Master Card'), ('paypal', 'PayPal'), ('bankTransfer_DE', 'German Banktransfer')], max_length=50),
        ),
    ]
