# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyengo', '0016_auto_20160707_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('giropay', 'GiroPay'), ('bcmc', 'Bancontact card'), ('visa', 'Visa'), ('ebanking_FI', 'Finnish E-Banking'), ('diners', 'Diners Club'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('directEbanking', 'SofortUberweisung'), ('amex', 'Amex'), ('bankTransfer_IBAN', 'International Bank Transfer (IBAN)'), ('paypal', 'PayPal'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('mc', 'Master Card'), ('bankTransfer', 'All banktransfers'), ('ideal', 'iDEAL'), ('maestro', 'Maestro'), ('elv', 'ELV'), ('dotpay', 'Dotpay'), ('sepadirectdebit', 'SEPA Direct Debit'), ('bankTransfer_DE', 'German Banktransfer'), ('card', 'All debit and credit cards'), ('discover', 'Discover')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recurringpaymentresult',
            name='result_code',
            field=models.CharField(choices=[('Authorised', 'Authorised'), ('Received', 'Received'), ('Refused', 'Refused'), ('Error', 'Error')], max_length=30),
        ),
        migrations.AlterField(
            model_name='session',
            name='country_code',
            field=models.CharField(choices=[('GB', 'United Kingdom'), ('DE', 'Germany'), ('NL', 'Netherlands'), ('BE', 'Belgium')], max_length=2),
        ),
        migrations.AlterField(
            model_name='session',
            name='page_type',
            field=models.CharField(choices=[('multiple', 'Multiple'), ('single', 'Single'), ('skip', 'Skip')], default='skip', max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='recurring_contract',
            field=models.CharField(blank=True, choices=[('ONECLICK', 'One click'), ('RECURRING', 'Recurring'), ('RECURRING,ONECLICK', 'Recurring and One click (user chooses)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('hpp_regular', 'HPP Regular'), ('api_recurring', 'API Recurring'), ('hpp_recurring', 'HPP Recurring')], max_length=25),
        ),
        migrations.AlterField(
            model_name='session',
            name='shopper_locale',
            field=models.CharField(blank=True, choices=[('en_GB', 'English (United Kingdom)'), ('de_DE', 'German (Germany)'), ('nl_NL', 'Dutch (Holland)'), ('fr_BE', 'French (Belgium)'), ('nl_BE', 'Dutch (Belgium)')], default='nl_NL', max_length=5),
        ),
        migrations.AlterField(
            model_name='sessionallowedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('giropay', 'GiroPay'), ('bcmc', 'Bancontact card'), ('visa', 'Visa'), ('ebanking_FI', 'Finnish E-Banking'), ('diners', 'Diners Club'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('directEbanking', 'SofortUberweisung'), ('amex', 'Amex'), ('bankTransfer_IBAN', 'International Bank Transfer (IBAN)'), ('paypal', 'PayPal'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('mc', 'Master Card'), ('bankTransfer', 'All banktransfers'), ('ideal', 'iDEAL'), ('maestro', 'Maestro'), ('elv', 'ELV'), ('dotpay', 'Dotpay'), ('sepadirectdebit', 'SEPA Direct Debit'), ('bankTransfer_DE', 'German Banktransfer'), ('card', 'All debit and credit cards'), ('discover', 'Discover')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionblockedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('giropay', 'GiroPay'), ('bcmc', 'Bancontact card'), ('visa', 'Visa'), ('ebanking_FI', 'Finnish E-Banking'), ('diners', 'Diners Club'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('directEbanking', 'SofortUberweisung'), ('amex', 'Amex'), ('bankTransfer_IBAN', 'International Bank Transfer (IBAN)'), ('paypal', 'PayPal'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('mc', 'Master Card'), ('bankTransfer', 'All banktransfers'), ('ideal', 'iDEAL'), ('maestro', 'Maestro'), ('elv', 'ELV'), ('dotpay', 'Dotpay'), ('sepadirectdebit', 'SEPA Direct Debit'), ('bankTransfer_DE', 'German Banktransfer'), ('card', 'All debit and credit cards'), ('discover', 'Discover')], max_length=50),
        ),
    ]
